from django.conf.urls.defaults import *

urlpatterns = patterns('toolbar_buttons.toolbar_buttons_web.tbutton_maker',
    url(r'^custom/create-addon/$', 'views.create', name='tbutton-create'),
    url(r'^statistics/', 'views.statistics', name='tbutton-statistics'),
    url(r'^custom/$',
        'views.index', name='tbutton-custom'),
    url(r'^custom/(?P<locale_name>[a-z]{2}(-[A-Z]{2})?)/$',
        'views.index', name='tbutton-custom'),
    url(r'^custom/(?P<locale_name>[a-z]{2}(-[A-Z]{2})?)/(?P<applications>[a-zA-Z,]+)/$',
        'views.index', name='tbutton-custom'),
    url(r'^list_buttons/$',
        'views.list_buttons', name='tbutton-list'),
    url(r'^list_buttons/(?P<locale_name>[a-z]{2}(-[A-Z]{2})?)/$',
        'views.list_buttons', name='tbutton-list'),
    url(r'^list_buttons/(?P<locale_name>[a-z]{2}(-[A-Z]{2})?)/(?P<applications>[a-zA-Z,]+)/$',
        'views.list_buttons', name='tbutton-list'),
    url(r'^custom_update', 'views.old_update'),
    url(r'^update.rdf', 'views.update', name='tbutton-update'),
    url(r'^make_button/', 'views.make', name='tbutton-make-button'),
)
